name: github-actions-demo
on:
  - workflow_dispatch
  - push:
      branches:
        - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: enable pnpm
        run: corepack enable pnpm
      - name: pnpm version
        run: pnpm -v
      - name: install dependencies
        run: pnpm i
      - name: compile ts file
        run: tsc -p tsconfig.json
      - name: list output files
        run: ls -lh out
      - name: show out/index.js file content
        run: cat out/index.js

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: release
          commit_message: ${{ github.event.head_commit.message }}
