name: github-actions-demo
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: enable pnpm
        run: corepack enable pnpm
      - name: install dependencies
        run: pnpm i
