name: github-actions-demo
on:
  push
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: enable pnpm
        run: corepack enable pnpm
      - name: install dependencies
        run: pnpm i
